# MATH 210 Project I

## Predicting and Understanding Discrete Dynamical systems using sympy.matrices

### by Agnes Ouko

SymPy is one of the core scientific computing packages in Python and the subpackage sympy.matrices addresses a number of computations, from creating  basic matrices to working with matrices in solving real world problems. Some of the computational problems addressed are (see the [documentation](http://docs.sympy.org/latest/modules/matrices/matrices.html)):

1. Creating Matrices
2. Basic Manipulation of Matrices
3. Operations on entries
4. Linear algebra
5. MatrixBase Class Reference
6. Matrix Exceptions Reference
7. Matrix Functions Reference
8. Numpy Utility Functions reference

A [Dynamical system](https://en.wikipedia.org/wiki/Dynamical_system_(definition) can be described as a system whose state evolves with time over a state space according to a fixed rule while a discrete dynamical system is a dynamical system whose state evolves over state space in **discrete** time steps according to a fixed rule. (see [Documentation](http://mtl.math.uiuc.edu/book/export/html/77))

Our main goal in this notebook is to use linear algebra in predicting and understanding the long-term behaviour or *evolution* of a dynamical system described by a difference equation $\mathbf{x_{k+1}} = A \mathbf{x_k}$. In particular, we will explore how to create matrices in sympy, perform basic operations like addition and multiplication of matrices, perform operations on the matrices entries and finally use all these operations in performing a few real life case scenarios of the behaviour of discrete dynamical systems.



## Contents

1. Creating Matrices in sympy
2. Basic Manipulation of Matrices
3. Operation on entries
4. Linear Algebra
5. Modelling and analyzing real-world issues:
    * Population predictions
    * Predator prey model
6. Symbololism in SymPy
7. Exercise


In [1]:
import sympy.matrices as sm
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sympy import init_printing
init_printing()

## 1. Creating Matrices in sympy

We can either create matrices in sypmy or use Numpy arrays to create matrices. We are going to do both and choose the easiest and most convenient method of doing this. 

Let's us create $3 x 3$ matrices using both numpy arrays and sympy matrix

In [3]:
M = Matrix([[1,2,3],[1,2,3]])
M

⎡1  2  3⎤
⎢       ⎥
⎣1  2  3⎦

In [4]:
M = np.array([[1,2,3],[1,2,3]])
M

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:



M = np.random.randint(1,3,[3,3])
print(M)
M.shape

[[2 2 1]
 [1 2 2]
 [2 1 1]]


In [6]:
# this function can be used to create unit matrix different sizes

def f(i,j):
    if i == j:
        return 1
    else:
        return 0

In [7]:
Matrix(4,4,f)

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

In [8]:
Matrix(3,2,f)

⎡1  0⎤
⎢    ⎥
⎢0  1⎥
⎢    ⎥
⎣0  0⎦

In [9]:
Matrix(5,5,f)

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

From the above examples, we see that we can either predetermine what values we want in our matrices or we can use `np.random.randint` to quickly generate matrices with random values. We can also use functions to create any kind of matrces we want.

There are also a couple of special constructors for quick matrix construction: 
1. `eye` is the identity matrix, 
2. `zeros` and `ones` for matrices of all zeros and ones, respectively
3. `diag` to put matrices or elements along the diagonal:



In [10]:
eye(4)

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

In [11]:
zeros(3)

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

In [12]:
zeros(2,3)

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [13]:
ones(3)

⎡1  1  1⎤
⎢       ⎥
⎢1  1  1⎥
⎢       ⎥
⎣1  1  1⎦

In [14]:
ones(2,3)

⎡1  1  1⎤
⎢       ⎥
⎣1  1  1⎦

In [15]:
diag(1,Matrix([[1,2,3],[3,4,5]]))

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  2  3⎥
⎢          ⎥
⎣0  3  4  5⎦

In [16]:
diag(3,Matrix([[1,2,3],[3,4,5]]))

⎡3  0  0  0⎤
⎢          ⎥
⎢0  1  2  3⎥
⎢          ⎥
⎣0  3  4  5⎦

In [17]:
diag?


## 2. Basic Manipulation of Matrices

While learning to work with matrices, let’s choose one where the entries are readily identifiable. One useful thing to know is that while matrices are 2-dimensional, the storage is not and so it is allowable - though one should be careful - to access the entries as if they were a 1-d list. When working with matrices, each value has its unique position in the matrix and the position starts from `0` to `n`- `n` being the last position in the matrix, which contains the last value of the matrix.

In [ ]:
M = Matrix(2, 3, [1, 2, 3, 4, 5, 6])
M

In [ ]:
M[4] # this is the value in the fourth position of our matrix M

In [ ]:
M[0]

 We can also use the `row and column positons` to find the corresponding value on that position.

In [ ]:
M[0,0]

In [ ]:
M[0,2]

Since this is Python we’re also able to slice submatrices; slices always give a matrix in return, even if the dimension is $1 x 1$:

In [ ]:
M[0:2, 0:2]

In [ ]:
M[0:3, 0:1]

In [ ]:
M[0:,2]

In [ ]:
M[0:1,2]

You cannot access rows or columns that are not present unless they are in a slice, for example:


In [ ]:
M[:,10]

# we get an error that basically tells us that the index 10 
# is out of bounds for axis 1 with size 3

All the standard arithmetic operations are supported, as well as some vector operations

In [ ]:
P = Matrix(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]))

P

In [ ]:
P + P

In [ ]:
P * P # this is the same as P**2

In [ ]:
P - P

In [ ]:
P**3

In [ ]:
P2  = Matrix(4,1,[1,5,0,3])

P2

In [ ]:
P * P2 # this is possible only when the number of columns in P are equal to the number of rows in P2

In [ ]:
P.row_del(0) # we can delete an entire row from a matrix
P

In [ ]:
P.col_del(1)  # we can delete an entire column from a matrix
P

In [ ]:
v1 = Matrix([1,2,3])
v2 = Matrix([4,5,6])
v3 = v1.cross(v2)


In [ ]:
v1.dot(v2) # This is the dot product operation

In [ ]:
v2.dot(v3)

In [ ]:
v3

In [ ]:
v1.dot(v3)

We've seen that the row_del() and col_del() operations don’t return a value - they simply change the matrix object. We can also ‘’glue’’ together matrices of the appropriate order:

In [ ]:
M1 = eye(3)
M2 = zeros(3, 4)
M1.row_join(M2)


## 3. Operations on entries

We can multiply our matrices with scalars or we can apply functions to our matrices using `applyfunc()`.

In [ ]:
M = eye(3)
M

In [ ]:
2*M

In [ ]:
f = lambda x: 2*x

eye(3).applyfunc(f)

We can also use the substitution function. Here, we declare a matrix with symbolic entries then substitute a value. 

**Note:** we can substitute anything, even another symbol!!!

In [ ]:
from sympy import Symbol

In [ ]:
x = Symbol('x')
M = eye(3) * x
M

In [ ]:
M.subs(x,4)

In [ ]:
y = Symbol('y')
M.subs(x,y)

## 4. Linear Algebra

Now that we know how to create, manipulate and operate on matrix entries, let us get into the fun part. The first thing we will compute is the determinant of the matrix. There are afew ways to do this depending on the size of the matrix, we will only look at the in-built sympy function for computing determinants.

    * Use the in-built determinant function for matrices of size $2 x 2$ and above

## a). Use the in-built determinant function

In [ ]:
M = Matrix(([1,2,3],[3,6,2],[2,0,1]))
M.det()

In [ ]:
M2 = eye(2)
M2.det()

In [ ]:
M3 = Matrix(([1,0,0,0], [1,0,0,0], [1,0,0,0],[1,0,0,0]))

M3.det()

Another common operation is the inverse: In SymPy, this is computed by Gaussian elimination by default (for dense matrices) but we can specify it be done by [$LU$ decomposition](https://en.wikipedia.org/wiki/LU_decomposition) as well:

In [ ]:
T = Matrix(([1,2,3,4],[3,6,2,3],[2,0,1,5],[3,4,5,7]))
T

In [ ]:
T.inv()

In [ ]:
T.inv(method= "LU")

In [ ]:
T * T.inv(method= "LU")

We can solve the system $Ax = b$ by passing the b vector to the matrix A's LUsolve function. Here we will brak the problem down so that we choose A and x then bultiply to get b. Then we can solve for x and check that it's correct:

In [ ]:
L = Matrix([[2,3,5],[3,6,2],[8,3,6]])

x = Matrix(3,1,[3,7,5])

b = L*x

soln = L.LUsolve(b)

soln

Now that we know how this works, let us try an example of our own:

$A1*x = b1$

$A1 = \begin{bmatrix}           
       2 & 3 & 5 \\[0.3em]
       3 & 6 & 6 \\[0.3em]
       8 & 3 & 6
     \end{bmatrix} $
     
$b1 = \begin{bmatrix}
       1 \\ 2 \\ 3 
     \end{bmatrix}$
     
**$x$** = ?


In [ ]:
A1 = Matrix([[2,3,5],[3,6,2],[8,3,6]])

b1 = Matrix(3,1,[1,2,3])


ans = A1.LUsolve(b1)

ans


We can calculate the character polynomial of a matrix using the in-built function $.charpoly()$ and from the character polynomial we can find the eigenvalues and their respective eigenvectors.

In [ ]:
A2 = Matrix([[1,2,1],[6,-1,0],[-1,-2,-1]])

A2

In [ ]:
a = A2.charpoly()
a

In [ ]:
A2.eigenvals()

In [ ]:
A2.eigenvects()

## 5. Modelling and analyzing real-world problems:

Now that we have the basics and the manipulation of matrices out of the way, let us now use this information in working out some real-world examples. We are going to look at two major areas:

   #### 1. Population predictions
   #### 2. Predator prey model
 

## 1. Population Predictions


Using the Markov process, we can estimate the population of Vancouver and Richmond, by considering their migration patterns. 

Let's assume that every year 5% of the population of Richmond moves to Vancouver and 10% of the Vancouver population moves to Richmond. We neglect all other effects on the populations of the two cities: no one gets born or dies, no one moves elsewhere, no one moves from outside Vancouver or Richmond to one of the two cities. Let us measure population size in multiple
of 1,000.
To describe the populations, we will use population vectors. These will be
vectors $\binom{v}{r}$ where v is the Vancouver population and r the Richmond population.
Thus a population vector of $\binom{300}{100}$ represents a population of 300,000 in Vancouver and 100,000 in Richmond.

If the population vector in the current year, 2007, is $\binom{300}{100}$, then next year
the population vector will be $\binom{275}{125}$. This is because 30 kilo-people (10% of 300 kilo-people) move from Vancouver to Richmond and 5 kilo-people (5% of 100 kilo-people) move from Richmond to Vancouver, resulting in a net gain of 25 kilo-people for Richmond.

$\begin{pmatrix} v_{n+1} \\ r_{n+1} \end{pmatrix}$ = $\begin{pmatrix} .9v_n + .05r_n \\ .1v_n + .95r_n \end{pmatrix}$ = $\begin{pmatrix} .9 & .05 \\ .1 & .95 \end{pmatrix}$ $\begin{pmatrix} v_n \\ r_n \end{pmatrix}$

In [18]:
B = Matrix([[0.9, 0.05],[0.1, 0.95]])

B

⎡0.9  0.05⎤
⎢         ⎥
⎣0.1  0.95⎦

Let us plot the population development for this example:


In [19]:
# n = 0
C = Matrix([[300],[100]])
C

⎡300⎤
⎢   ⎥
⎣100⎦

In [20]:
# n = 1
C1 = B * C
C1


⎡275.0⎤
⎢     ⎥
⎣125.0⎦

In [21]:
# n = 2
C2 = B * C1
C2

⎡253.75⎤
⎢      ⎥
⎣146.25⎦

In [22]:
# n = 3
C3 = B * C2
C3

⎡235.6875⎤
⎢        ⎥
⎣164.3125⎦

In [23]:
B.eigenvals()

In [24]:
# this is the matrix we get after subtracting the identity matrix from B
# (B - lambda*I)
vec_matrix = B - eye(2) 
vec_matrix

⎡-0.1  0.05 ⎤
⎢           ⎥
⎣0.1   -0.05⎦

We row reduce the vec_matrix to row reducing echeleon form using the [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) to find the values of v and r. In this case we get the matrix: $$\begin{pmatrix} 1 & 0.5 \\ 0 & 0 \end{pmatrix}$$

After row reduction of the eigenvector, we get:

$v = 0.5r$ and 

$r = r \space (free)$

$v + r = 300 + 100 = 400$

$v - 0.5 = 0$

$v + r = 400$

$\binom{v}{r}$ = $\binom{133}{267}$

## 2. Preadtor Prey  model

The predator-prey problem refers to an ecological system in which we have two species, one of which feeds on the other. This type of system has been studied for decades and is known to exhibit interesting dynamics. A simple model for this situation can be constructed using a `discrete-time model` by keeping track of the rate of births and deaths of each species. The following [Predator-prey simulation](http://www.ahahah.eu/trucs/pp/) can kind of show us the behaviour of predators and prey in their natural habitat. Let us use an example to illustrate how this works:

#### Example: 
The spotted owl dines mainly on flying squirrels. Suppose the predator-prey matrix for these two populations is given by the matrix, $"A"$. Show that if the predation parameter, $p = 0.325$, both populations grow. Estimate the long-term growth rate and the eventual ratios of owls to flying squirrels.


In [25]:
p = 0.325

A = Matrix([[0.4, 0.3],[-p, 1.2]])

A

⎡ 0.4    0.3⎤
⎢           ⎥
⎣-0.325  1.2⎦

Denote the owl and squirrel populations at time "k" by the following vector where "k" is some unit of time: seconds, months, years, etc.

$x_k = \begin{pmatrix} O_k \\ S_k \end{pmatrix}$

$O_{k+1} = 0.4O_k + 0.3S_k $

$S_{k+1} = -pO_k + 1.2S_k$

If there are no squirrels, then 40% of the owls die after the expiration of the first unit of time. If there are no owls, then growth rate is 20% for the squirrels

In [26]:
A.charpoly()

In [27]:
A.eigenvals()

In [28]:
A.eigenvects()

⎡⎛         ⎡⎡2.0⎤⎤⎞  ⎛         ⎡⎡0.461538461538462⎤⎤⎞⎤
⎢⎜0.55, 1, ⎢⎢   ⎥⎥⎟, ⎜1.05, 1, ⎢⎢                 ⎥⎥⎟⎥
⎣⎝         ⎣⎣1.0⎦⎦⎠  ⎝         ⎣⎣       1.0       ⎦⎦⎠⎦

From the following equation:
$$\mathbf{x}_k = c_1 * (\lambda_1)^k * v_1 + c_2 * (\lambda_2)^k * v_2 + ... + c_n * (\lambda_n)^k * v_n $$

where $\lambda$ is the eigenvalue of a matrix, $v_1$ is the eigenvector corresponding to the eigenvalue of the vector and $c$ is any arbitrary constant; we can be able to model and tell how the populations of the prey and predators will change


$$\mathbf{x}_k = c_1 * (0.55)^k * \begin{pmatrix} 2 \\ 1 \end{pmatrix} + c_2 * (1.05)^k * \begin{pmatrix} 0.461538461538462 \\ 1 \end{pmatrix} $$

The dominant term here is $\lambda = 1.05$ because:

$\lim_{k \to \infty} (1.05)^k = \infty$ and $\lim_{k \to \infty} (0.55)^k = 0$


In [ ]:
# let us try and covert vector 2 into a matrix with integers
vec2 = Matrix([[0.461538461538462],[1]])

vec2

In [ ]:
int_vec2 = vec2 * int(13)

int_vec2

Eventually, there will be 6 (thousand) owls for every 13 (thousand) flying squirels and both populations will grow at the same *5%* annual rate.

## Symbolism in SymPy

In [ ]:
from sympy import symbols 

SymPy is all about construction and manipulation of expressions. By the term expression we mean mathematical expressions represented in the Python language using SymPy’s classes and objects. Expressions may consist of symbols, numbers, functions and function applications (and many other) and operators binding them together (addiction, subtraction, multiplication, division, exponentiation). In this case we are going to look at mostly symbols; they allow for a greater level of expresiveness that can be embedded directly in the code, making it an excellent tool for science teachers to formulate their ideas; if we look at Latex as a "static" descriptive language, the symbols module in sympy is "dynamic", in the sense that it is part of the running code. If Latex allows you to perfectly describe the mathematical formulaes and Python code allows you to implement the mathematical concept then sympy symbols is the best way to have both of them : expressivenes + implementation. 


In [ ]:
m = Symbol('m')
n = Symbol('n')
o = Symbol('o')
p = Symbol('p')

B = Matrix([[m,n],[o,p]])
B

In [ ]:
P = B.charpoly()
P

In [ ]:
B.subs({m:1,n:2,o:3,p:4})

In [ ]:
a,b,c,d = symbols('a,b,c,d')
e,f,g,h,i = symbols('e,f,g,h,i')

In [ ]:
A = Matrix([[a,b,c],[d,e,f],[g,h,i]])
A

In [ ]:
A.det()

In [ ]:
A.charpoly()

## 7. Exercises

#### 1. 
Consider an experiment where salt crystals are grown in a supersaturated solution. The mass of a crystal grows over 24 hours based on the updating function $$m_{t+1} = 1.5m_t$$ Given that the crystal originally has a mass of 10 grams, express the solution to this system, both in a table, graphically, and as a formula.


#### 2. 
Construct a stage matrix for an animal species has "2" life stages: juvenile (up to "1" year old) and adult. The female adults give birth to an average of "1.6" female juveniles. Each year, 30% of the juveniles survive to become adults and 80% of the adults survive.
 